### ISSUE TITLE
How do I use your mod to give you the recipes for a mod I'd like to see on the site?

### ISSUE THREAD

**Issue by PurpleHel** [andrewminer/crafting-guide-exporter#26]
I don't understand github very well, so have no idea how to turn github.com/andrewminer/crafting-guide-exporter into something I can use. I have a 1.10.2 and a 1.12.1 install I could work from. I'd like to see the recipes for Refined Storage on the site. Is there a jar for your exporter I can just drop into my mods folder? And then what do I do? Thanks!

**Comment by andrewminer** [comment]
This is really not ready for use yet, I'm afraid.  You'd do better to follow the instructions here: https://github.com/andrewminer/crafting-guide/wiki

**Comment by PurpleHel** [comment]
Ok, thanks. Unfortunately that's way beyond my skill set.
